[package]
name    = "sensu-plugins-rust-snmp"
version = "0.3.1"
authors = ["metalels <metalels86@gmail.com>"]

[[bin]]
name = "metrics-snmp"
path = "src/bin/metrics-snmp.rs"

[dependencies]
"getopts"     = "*"
"snmp"        = "*"
